### ISSUE TITLE
Please publish on F-Droid

### ISSUE THREAD

**Issue by baldurmen** [wger-project/android#3]
Hi!

Since all of your software is free software (yay!), why don't you publish it on F-Droid?

https://f-droid.org/wiki/page/Inclusion_Policy

**Comment by rolandgeider** [comment]
Yes, you are right, I should do it

**Comment by jbarascut** [comment]
+1. Very important

**Comment by rolandgeider** [comment]
I'm already getting people +1-ing issues, I've made it! :wink: 

(now seriously, when I'm back from my vacation I'll look how exactly to submit the app)

**Comment by ywecur** [comment]
How's it coming along?

**Comment by rolandgeider** [comment]
Sorry, I haven't gotten around to do this, I only looked into the submission process. I'm not sure if it wouldn't be easier (and better in the long run) to move to Cordova, which has a rather easy build process.

**Comment by marcosilva85** [comment]
Fdroid publishing would be great,
currently we lack a FOSS app in this genre (calories / food / exercise tracking).

This would be a really neat addition. Adding a new app to fdroid is really easy:
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by rolandgeider** [comment]
@marcosilva85 thanks for the link, I've taken a look. I've bumped this issue on my TODO list, as soon as I have something to show, I'll tell you guys.

**Comment by ywecur** [comment]
@rolandgeider If you want to build mobile apps that are "better", I've recently looked at and started learning [React native](https://facebook.github.io/react-native/) which seems to be the best option for building mobile apps. I could start a small project if you're interested in working with me.

**Comment by rolandgeider** [comment]
Thanks for the offer @ywecur. I had started learning angularJS and plan to "modernize" a handful of the pages and dialogs in the application, after all the REST API is already there and is currently barely used. I guess I can't convince you to switch sides? ;)

**Comment by ywecur** [comment]
@rolandgeider How about I convince you :) ! React native gets native feel and performance! [This video](https://www.youtube.com/watch?v=KVZ-P-ZI6W4) showcases this, and they go to great lengths to explain how this is better than current approaches!

Just my 2¢, but I'd highly suggest you watch the video :)

**Comment by rolandgeider** [comment]
I'll watch it :)

**Comment by rolandgeider** [comment]
I've watched the video and I have to admit that it is compelling ;) , I'll have to think about it (and in any case, we have to move that discussion to another issue)
