### ISSUE TITLE
Blank screen on launch

### ISSUE THREAD

**Issue by ywecur** [wger-project/android#5]
![screenshot_2016-01-18-13-58-57](https://cloud.githubusercontent.com/assets/6241555/12391986/e7dd98ac-bdeb-11e5-836f-c2879a881e5b.png)

Phone: Samsung GT-I8190N
Android version: 4.1.2
Screen size: 4.0″

**Comment by rolandgeider** [comment]
The android app just shows the web version, so this is strange. Does this happened every time or only sometimes?

**Comment by ywecur** [comment]
Every time.

**Comment by ywecur** [comment]
Not än issue anymore :) Might have been some connection issues
